#!/usr/bin/env bash
# A script that installs nginx server on an ubuntu linux distro.
# The installed server listens to port 80 (HTTP) for connection
# And serves a default page index.html on the HTTP  GET request.

sudo apt-get  -y update

sudo apt-get install  -y nginx

echo 'Hello World!' | sudo tee  /var/www/html/index.html

sudo service nginx restart
